In [3]:
# Numpy is a powerful N dimentional array object with advanced array slicing methods and array reshaping methods , basic linear algebra 
# basic fourier transformations 
# sophisticated random number capabilities 
# tools for integrating fortran code 
# toold for integrating C/C++ code
# numpy is suited for many applications :
#     image processing
#     signal processing 
#     linear algebra
    
    

Numpy Basic


In [2]:
import numpy as np
li=[1,2,3,4,5,6,8]
arr1=np.array(li)
type(arr1)

numpy.ndarray

In [4]:
for x in arr1:
    print(x)

1
2
3
4
5
6
8


In [6]:
arr1.dtype

dtype('int32')

# Np array data type


In [7]:
arr1=np.array(li,dtype=np.int64)

In [8]:
arr1.dtype


dtype('int64')

In [9]:
li=[1,2,3,4,5.9]

In [10]:
arr1=np.array(li)

In [11]:
arr1.dtype


dtype('float64')

In [12]:
arr1=np.array(li,dtype=np.int64)

In [13]:
arr1


array([1, 2, 3, 4, 5], dtype=int64)

In [18]:
#Number of dimensions
arr1.ndim

(5,)

In [20]:
#Shape of the array
arr1.shape

(5,)

In [23]:
#2d array
arr2=np.array([[10,20],[20,30],[30,40]])
arr2


array([[10, 20],
       [20, 30],
       [30, 40]])

In [24]:
arr2.shape

(3, 2)

In [25]:
arr2.ndim

2

In [26]:
arr2[0].shape

(2,)

In [36]:
arr3=np.arange(24)
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [37]:
arr3[-1]

23

In [41]:
arr3=arr3.reshape(4,6)
arr3

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [42]:
arr3=np.arange(24).reshape(4,6)

In [43]:
arr3


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [49]:
#Array arithmetic here 1 is added to each element
arr1=np.arange(8)
arr2=arr1+1
#operation + is broadcasted to each element of the array

In [46]:
arr2


array([1, 2, 3, 4, 5, 6, 7, 8])

In [47]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7])

In [50]:
arr1**3

array([  0,   1,   8,  27,  64, 125, 216, 343], dtype=int32)

In [51]:
arr1=np.arange(8)
arr2=np.arange(8,16)
arr3=arr1+arr2

In [54]:
arr3


array([ 8, 10, 12, 14, 16, 18, 20, 22])

In [56]:
arr4=arr1[2:6]
arr4


array([2, 3, 4, 5])

In [57]:
arr4[0]=90 # this will change

In [60]:
arr1

array([ 0,  1, 90,  3,  4,  5,  6,  7])

In [61]:
arr4=arr1[2:6].copy()

In [62]:
arr4[0]=999

In [63]:
arr4

array([999,   3,   4,   5])

In [64]:
arr1

array([ 0,  1, 90,  3,  4,  5,  6,  7])

In [67]:
arr4=np.arange(36).reshape(6,6)
arr4
arr4[1][1]
arr4[2:5,2:5]=-1
arr4


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, -1, -1, -1, 17],
       [18, 19, -1, -1, -1, 23],
       [24, 25, -1, -1, -1, 29],
       [30, 31, 32, 33, 34, 35]])

In [69]:
arr4=np.zeros(10,dtype=int)
arr4

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [82]:
arr5=np.zeros((4,3))


In [83]:
arr5


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [84]:
arr4=np.identity(4)

In [85]:
arr4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [88]:
arr5=np.random.random(24).reshape(4,6) #np.random is a submodule of np

In [95]:
arr5=np.random.randn(10)
arr5

array([ 0.97787614, -2.77702395,  0.01259068, -0.70576676,  2.62821463,
       -0.21054387, -0.88153636,  0.09598972,  0.33681064, -0.16568617])

In [98]:
marks=np.array([50,90,42,75,49])
masks=np.array([True,False,True,False,False,])

In [100]:
marks[masks] # if we pass a boolean array of size size to the array then it will return only those elmenets
#whose positions are true

array([50, 42])

In [101]:
marks>50 #this generates a boolean array and that can be used as an index


array([False,  True, False,  True, False])

In [106]:
marks[(marks>50) & (marks<80)] #boolean and

array([75])

In [107]:
np.max(marks)

90

In [108]:
np.min(marks)

42

In [109]:
np.mean(marks)

61.2

In [111]:
np.median(marks)

50.0

In [113]:
np.argmax(marks)

1

In [114]:
np.argmax.__doc__


'\n    Returns the indices of the maximum values along an axis.\n\n    Parameters\n    ----------\n    a : array_like\n        Input array.\n    axis : int, optional\n        By default, the index is into the flattened array, otherwise\n        along the specified axis.\n    out : array, optional\n        If provided, the result will be inserted into this array. It should\n        be of the appropriate shape and dtype.\n\n    Returns\n    -------\n    index_array : ndarray of ints\n        Array of indices into the array. It has the same shape as `a.shape`\n        with the dimension along `axis` removed.\n\n    See Also\n    --------\n    ndarray.argmax, argmin\n    amax : The maximum value along a given axis.\n    unravel_index : Convert a flat index into an index tuple.\n\n    Notes\n    -----\n    In case of multiple occurrences of the maximum values, the indices\n    corresponding to the first occurrence are returned.\n\n    Examples\n    --------\n    >>> a = np.arange(6).reshape

In [120]:
mat=np.arange(16).reshape(4,4)

In [121]:
np.linalg.det(mat)

-2.9582283945787796e-30

In [122]:
mat

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [126]:
mat1=np.arange(5,9).reshape(2,2)
mat1

array([[5, 6],
       [7, 8]])

In [124]:
np.linalg.det(mat1)

-1.999999999999999

In [5]:
import numpy as np
v1=np.array([10,12,13])
v2=np.array([10,10,10,])
np.dot(v1,v2)


350

In [10]:
mat1=np.arange(4).reshape(2,2)
mat1

array([[0, 1],
       [2, 3]])

In [8]:
np.linalg.inv(mat1)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

# 